<?php

namespace Tests\Feature\Api;

use App\Resource;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Str;
use Tests\TestCase;

class AuthTest extends TestCase
{
    public $user;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = new User();
        $token = Str::random(36);
        $user->id = '-'.substr(\Faker\Provider\Uuid::uuid(),0,-1);
        $user->name ='guest';
        $user->email = $user->id.'@diandi.org';
        $user->api_token = $token;
        $user->save();
        $this->user = $user;
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testGetAuth()
    {
        $response = $this->json('GET','/api/resource/auth', ['api_token'=>$this->user->api_token],['Accept'=>'application/json']);
        $data = json_decode($response->getContent(), true);
        $response->assertStatus(200);
        $this->assertEquals(1,$data['status']);

    }
    public function testGetGetAuthWithWrongToken()
    {
        $response = $this->json('GET','/api/resource/auth', ['api_token'=>'abcd'],['Accept'=>'application/json']);
        $data = json_decode($response->getContent(), true);
        $response->assertStatus(401);
    }
    public function tearDown(): void
    {
        $this->user->delete();
        parent::tearDown(); // TODO: Change the autogenerated stub

    }


}
